export const SHOW = 'SHOW'
export const SORT_BY = 'SORT_BY'
export const PAGE = 'PAGE'
export const CATEGORY = 'CATEGORY'
export const ADD_BRAND = 'ADD_BRAND'
export const REMOVE_BRAND = 'REMOVE_BRAND'
export const ADD_COLOR = 'ADD_COLOR'
export const REMOVE_COLOR = 'REMOVE_COLOR'