export default [{
        id: 1,
        product: 1,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 2,
        product: 2,
        rating: 5,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 3,
        product: 3,
        rating: 5,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 4,
        product: 4,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 5,
        product: 5,
        rating: 5,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 6,
        product: 6,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 7,
        product: 7,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 8,
        product: 8,
        rating: 5,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 9,
        product: 9,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 10,
        product: 10,
        rating: 3,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 11,
        product: 11,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 12,
        product: 12,
        rating: 5,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 13,
        product: 13,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 14,
        product: 14,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 15,
        product: 15,
        rating: 5,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 16,
        product: 16,
        rating: 5,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 17,
        product: 17,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 18,
        product: 18,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 19,
        product: 19,
        rating: 4,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 20,
        product: 20,
        rating: 5,
        author: 'Artur',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
    {
        id: 21,
        product: 7,
        rating: 4,
        author: 'Envato',
        date: '12/12/2019',
        review: 'Each display features two FireWire 400 ports and two USB 2.0 ports, making attachment of desktop peripherals, such as iSight, iPod, digital and still cameras, hard drives, printers and scanners, even more accessible and convenient. Taking advantage of the much thinner and lighter footprint of an LCD, the new displays support the VESA.',
    },
];